import { Inter } from "next/font/google";
import "../globals.css";
import DashboardNav from "@/components/DashboardNav";
import Footer from "@/components/Footer";
import SIdebar from "@/components/SIdebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="bg-white">

      <body className={inter.className}>
        <DashboardNav />
        <div className="flex" >
          <SIdebar />
          <main className="w-[calc(100%_-_300px)] ml-[300px] ">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
